# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 21:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0004_auto_20160207_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
