# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0007_auto_20160208_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='categories',
            field=models.ManyToManyField(related_name='photographer', to='proto.Category'),
        ),
    ]
