# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:07
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0008_auto_20160208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
