# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proto', '0013_auto_20160214_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='photographersubscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 23, 597655, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 26, 85514, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 27, 694066, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 28, 925734, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 31, 334049, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 32, 518540, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 34, 69994, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 35, 526483, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 36, 974665, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographer',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographer',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 38, 462266, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 39, 886071, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 41, 238881, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 10, 42, 367044, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 17, 2, 10, 43, 918946, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='proto.Photo'),
        ),
        migrations.AddField(
            model_name='impression',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='impressions', to='proto.Photo'),
        ),
        migrations.AddField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
