# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0015_auto_20160217_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='last_name',
        ),
    ]
