# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0017_auto_20160221_0127'),
        ('proto', '0016_auto_20160220_2330'),
    ]

    operations = [
    ]
