# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0017_auto_20160221_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveManager',
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photographer',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photographersubscription',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/static/categories/placeholder.png', null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/static/categories')),
        ),
    ]
