# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 16:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/static/categories/placeholder.png', null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/static/categories')),
        ),
    ]
