# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0018_auto_20160221_2206'),
        ('proto', '0019_auto_20160221_1621'),
    ]

    operations = [
    ]
