# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0020_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
