# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0021_auto_20160223_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='like',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
