# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0022_auto_20160323_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='ip',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='ip',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
