# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0023_auto_20160323_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
